{{- if .Values.global.docker.config.path }}
kind: ExternalSecret
apiVersion: kubernetes-client.io/v1
metadata:
  name: {{ template "pegaRegistrySecret" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
spec:
  type: kubernetes.io/dockerconfigjson
  backendType: secretsManager
  data:
    - key: {{ .Values.global.docker.config.path }}
      name: .dockerconfigjson
{{- else }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pegaRegistrySecret" }}
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
{{- end }}
